// movie action
export const FETCH_THEATERS_MOVIES = 'FETCH_THEATERS_MOVIES';
export const FETCH_COMINGSOON_MOVIES = 'FETCH_COMINGSOON_MOVIES';
export const FETCH_TOP_MOVIES = 'FETCH_TOP_MOVIES';
export const FETCH_MOVIES_ERROR = 'FETCH_MOVIES_ERROR';

export const FETCH_CELEBRITY = 'FETCH_CELEBRITY';


// activity action
export const FETCHING_ACTIVITIES = 'FETCHING_ACTIVITIES';
export const RECEIVE_ACTIVITIES = 'RECEIVE_ACTIVITIES';
export const CHANGE_ACTIVITIES_HASMORE = 'CHANGE_ACTIVITIES_HASMORE';
export const FETCH_ACTIVITIES_ERROR = 'FETCH_ACTIVITIES_ERROR';