// movie action
export const FETCH_THEATERS_MOVIES = 'FETCH_THEATERS_MOVIES';
export const FETCH_COMINGSOON_MOVIES = 'FETCH_COMINGSOON_MOVIES';
export const FETCH_TOP_MOVIES = 'FETCH_TOP_MOVIES';
export const FETCH_MOVIES_ERROR = 'FETCH_MOVIES_ERROR';

export const FETCH_CELEBRITY = 'FETCH_CELEBRITY';